### ISSUE TITLE
🎨 「咲想」UI/UXデザインシステム設計

### ISSUE THREAD

**Issue by wwlapaki310** [wwlapaki310/sakisou#5]
## 🎯 目標
「咲想」ブランドに相応しい感動的なUI/UXデザインシステムを設計する

### ブランドアイデンティティ
- **コア価値**: 想いを咲かせる、感情の可視化、心をつなぐ
- **感情体験**: 温かさ、優しさ、美しさ、上品さ
- **文化的背景**: 日本の美意識、花言葉文化、現代とのブリッジ

### ターゲット体験設計
- **感動の瞬間**: 「想いが花になった！」という驚きと喜び
- **直感的操作**: 言葉を入力するだけで美しい結果が得られる
- **シェアしたくなる**: 友人に見せたくなる美しさ

### メインカラー（感情別）
```css
/* 基本パレット */
:root {
  /* Primary - 桜色系 */
  --sakura-pink: #E8B4CB;      /* メインピンク */
  --sakura-light: #F5D7E3;     /* 淡いピンク */
  --sakura-deep: #D499B9;      /* 濃いピンク */
  
  /* Secondary - 自然色系 */
  --cream: #F7F3E9;            /* クリーム */
  --sage-green: #6B8E5A;       /* 葉緑色 */
  --moss-green: #4F6B43;       /* 深緑 */
  
  /* Text */
  --text-primary: #2C2C2C;     /* 墨色 */
  --text-secondary: #5A5A5A;   /* グレー */
  --text-light: #8A8A8A;       /* 薄グレー */
  
  /* 感情表現色 */
  --love-red: #D67B7B;         /* 愛情 */
  --gratitude-yellow: #F4E4A6; /* 感謝 */
  --apology-blue: #A6C8E4;     /* 謝罪 */
  --hope-orange: #F2B366;      /* 希望 */
  --sadness-purple: #B8A6D6;   /* 悲しみ */
}
```

### 感情別カラーマッピング
- **愛情・情熱**: 温かい赤・ピンク系
- **感謝・喜び**: 明るい黄・オレンジ系  
- **謝罪・反省**: 冷静な青・紫系
- **希望・応援**: エネルギッシュなオレンジ系
- **別れ・悲しみ**: 落ち着いた紫・藍系

### ロゴアイデア
1. **文字ベース**: 
   - 「咲想」を美しい書体で
   - 「咲」の文字に花のモチーフを組み込み
   - 筆文字風だが現代的なタッチ

2. **シンボルマーク**:
   - 開花する桜の花びら
   - ハート型に配置された花弁
   - AI的な幾何学模様と花の融合

3. **カラーバリエーション**:
   - フルカラー版
   - モノクロ版
   - 単色版（各感情色）

### ロゴサイズ展開
- **ヘッダー用**: 横長バージョン
- **アプリアイコン**: 正方形、シンプル
- **SNSシェア用**: 背景込みバージョン

### 1. メイン画面フロー
```
[スプラッシュ] → [ホーム] → [感情入力] → [花推薦] → [画像生成] → [結果・シェア]
     ↓
[ログイン/登録] ← → [履歴] ← → [設定]
```

#### ホーム画面
```
┌─────────────────────────┐
│  🌸 咲想                 │ ← ヘッダー
├─────────────────────────┤
│                         │
│    [美しい背景グラデーション]  │
│                         │
│     今日の想いを         │ ← キャッチコピー
│     花に込めて           │
│                         │
│  ┌─────────────────┐    │
│  │  想いを入力...    │    │ ← メイン入力
│  └─────────────────┘    │
│                         │
│    [感情を花に変換] ボタン    │ ← CTA
│                         │
│  最近の花束   過去の想い     │ ← 履歴アクセス
└─────────────────────────┘
```

#### 感情入力画面
```
┌─────────────────────────┐
│ ← 戻る    咲想    設定 ≡  │
├─────────────────────────┤
│                         │
│  あなたの想いを教えてください │
│                         │
│ ┌─────────────────────┐ │
│ │                     │ │ ← 大きなテキストエリア
│ │  ここに自由に        │ │
│ │  気持ちを書いて...    │ │
│ │                     │ │
│ └─────────────────────┘ │
│                         │
│  💡 例: 「ありがとう」     │ ← 入力例
│      「ごめんなさい」     │
│                         │
│     [想いを花に] 🌸       │ ← 送信ボタン
└─────────────────────────┘
```

#### 画面遷移
- **ページトランジション**: 花びらが舞い散る効果
- **ローディング**: 花が咲くアニメーション
- **結果表示**: フェードイン + 上から下へ

#### マイクロインタラクション
- **ボタンタップ**: 花びらエフェクト
- **入力時**: 文字に合わせて色変化
- **成功時**: キラキラエフェクト

### 感情可視化パターン
```css
/* 愛情表現 */
.emotion-love {
  background: linear-gradient(45deg, #E8B4CB, #D67B7B);
  border-radius: 50% 40% 50% 40%;
  animation: heartbeat 2s infinite;
}

/* 感謝表現 */
.emotion-gratitude {
  background: radial-gradient(circle, #F4E4A6, #F2B366);
  animation: glow 3s ease-in-out infinite alternate;
}

/* 謝罪表現 */
.emotion-apology {
  background: linear-gradient(180deg, #A6C8E4, #7BA8D1);
  animation: gentle-wave 4s ease-in-out infinite;
}
```

### 花のビジュアル表現
- **バラ**: 情熱的な渦巻きパターン
- **桜**: 五角形ベースの柔らかな形
- **ひまわり**: 放射状のエネルギッシュなパターン
- **カスミソウ**: 小さな点の集合体

### Phase 1: デザインシステム基盤
- [ ] カラーパレット定義・CSS変数化
- [ ] タイポグラフィシステム構築
- [ ] コンポーネントライブラリ設計
- [ ] アイコンセット作成

### Phase 2: ロゴ・ブランディング
- [ ] ロゴデザイン複数案作成
- [ ] ロゴファイナライズ（SVG, PNG）
- [ ] ファビコン・アプリアイコン作成
- [ ] ブランドガイドライン作成

### Phase 3: UI画面設計
- [ ] ワイヤーフレーム詳細化
- [ ] プロトタイプ作成（Figma）
- [ ] レスポンシブ対応確認
- [ ] アクセシビリティ検証

### Phase 4: アニメーション・エフェクト
- [ ] 花咲きアニメーション実装
- [ ] 感情カラーアニメーション
- [ ] ページトランジション
- [ ] マイクロインタラクション

### 視覚的インパクト
- **一目で分かる美しさ**: 開いた瞬間の「おおっ」という驚き
- **感情との共鳴**: ユーザーの気持ちに寄り添うデザイン
- **文化的深み**: 日本の美意識を現代的に表現

### ユーザビリティ
- **直感的操作**: 説明不要のシンプルなUI
- **感動体験**: 使うたびに嬉しくなる仕掛け
- **シェアしやすさ**: SNSで映える美しいビジュアル

### 技術的実装
- **高いパフォーマンス**: 60fps の滑らかなアニメーション
- **レスポンシブ対応**: あらゆるデバイスで美しく表示
- **アクセシビリティ**: 誰もが使いやすいデザイン

## ✅ 完了条件
- デザインシステムが完全に定義されている
- ロゴとブランドアイデンティティが確定している
- 全画面のワイヤーフレームが完成している
- アニメーション仕様が明確になっている
- 実装可能性が検証されている

## ⏰ 期限
6月23日 夜
